# Generated by Django 2.2.6 on 2019-11-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_foodcatagory_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcatagory',
            name='image',
            field=models.ImageField(default='caffee.png', upload_to=''),
        ),
    ]
