# Generated by Django 2.2.6 on 2019-11-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_foodcatagory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.CharField(max_length=6),
        ),
    ]
