# Generated by Django 2.2.6 on 2019-11-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('useremail', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('deliveryDate', models.CharField(max_length=255)),
                ('foodItemName', models.TextField()),
                ('quantity', models.CharField(max_length=255)),
                ('bill', models.CharField(max_length=255)),
                ('Payablebill', models.CharField(max_length=255)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
